apiVersion: v1
kind: Service
metadata:
  name: snowflake-service
  labels:
    app: snowflake-id-generator
spec:
  type: NodePort
  selector:
    app: snowflake-id-generator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
