apiVersion: v1
kind: Pod
metadata:
  name: snowflake-id-generator
spec:
  containers:
    - name: snowflake-id-generator
      image: snowflake:1.0
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
